### PR TITLE
Update gvm.hpp

### PR DESCRIPTION
**Pull request by ThirteenAG**
- IV\EFLC detection
- aslr

### CODE REVIEW

**Comment by ThirteenAG** [comment]
Better check everything, who knows what I broke there :D

**Comment by thelink2012** [comment]
seems gr8

**Comment by ckeleshi** [comment]
aslr in latest SA steam, too. It's 0x858EA8. I just can't figure out what version should it be...

**Comment by thelink2012** [comment]
@ClansChen Perhaps 3.0.1.0! Are you going to make a pull request for it?

**Pull request merged**
